FROM gcr.io/google.com/cloudsdktool/cloud-sdk
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt \
 && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
 && apt-get install -y nodejs \
 && apt-get install -y gettext \
 && npm i -g @dataform/cli