FROM gcr.io/google.com/cloudsdktool/cloud-sdk:latest
WORKDIR /ci
COPY requirements.txt ./
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN pip3 install --no-cache-dir -r requirements.txt \
 && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
 && apt-get install --no-install-recommends -y nodejs \
 && npm i -g @dataform/cli
