name: Doxygen

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doxygen
        run: sudo apt install doxygen -y
      - name: Run Doxygen
        run: doxygen Doxyfile
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs/${{ github.ref_name }}
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: false
          publish_branch: gh-pages
