# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Google Cloud Build script for bqutils
#
# This build script is used to deploy the open-source bqutil GitHub repository
# for every change pushed.
#
# Manual Execution:
# Use the below command to invoke the build manually. Note the substitutions for
# BRANCH_NAME and REVISION_ID. These variables are normally populated when the
# build is executed via build triggers but will be empty during manual
# execution. Dummy branch and revisions can be passed during manual execution so
# the artifacts can be uploaded upon build completion.
#
# gcloud builds submit . --config=cloudbuild.yaml
#

steps:
###########################################################
# Step 1: Deploy
###########################################################
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args: ['release/build.sh', '$BRANCH_NAME', '$_PR_NUMBER']

options:
  machineType: 'N1_HIGHCPU_8'
