steps:

- id: 'tf init and apply'
  name: 'hashicorp/terraform:1.0.0'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init --backend-config="bucket=${PROJECT_ID}-tfstate" -reconfigure
      terraform apply -auto-approve