workspace(name = "zetasql_helper")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
    name = "com_google_zetasql",
    strip_prefix = "zetasql-2020.07.01",
    urls = [
        "https://github.com/google/zetasql/archive/2020.07.01.tar.gz",
    ],
    patches = [
        "//patches:parser_visibility.patch",
        "//patches:resolver_visibility.patch",
    ],
)


load("@com_google_zetasql//bazel:zetasql_deps_step_1.bzl", "zetasql_deps_step_1")

zetasql_deps_step_1()

load("@com_google_zetasql//bazel:zetasql_deps_step_2.bzl", "zetasql_deps_step_2")

zetasql_deps_step_2()

load("@com_google_zetasql//bazel:zetasql_deps_step_3.bzl", "zetasql_deps_step_3")

zetasql_deps_step_3()

load("@com_google_zetasql//bazel:zetasql_deps_step_4.bzl", "zetasql_deps_step_4")

zetasql_deps_step_4()

