# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config {
    type: "view",
    schema: "dev_data_zone",
    name: "email_row_assertion_unit_test",
    tags:["email_row_assertion_unit_test","all_test"],
    assertions: {
        nonNull: ["input"],
        rowConditions: 
        [
            personal_info_assertions.test_email_validity("input")
        ]
    }
}


/*
    test_email_validity
    Return false is email is not in the foramt of abc@xyc.com or other
*/
SELECT "george.bail@google.com" AS input, True as expected_output UNION ALL
SELECT "among.us@amongus.net" AS input, True as expected_output   UNION ALL
SELECT "1736#$%.com" AS input, False as expected_output
