# Builds js_libs to your own GCS bucket for testing
# gcloud builds submit . --config=build_js_libs.yaml --substitutions=_JS_BUCKET="gs://YOUR_GS_BUCKET[/optional_sub_path]"
#

steps:
  ############################################################
  # Dynamically create the package.json file based off the libs
  # specified in the js_libs/js_libs.yaml file.
  ############################################################
- name: gcr.io/bqutil/bq_udf_ci
  id: generate_js_libs_package_json
  entrypoint: python3
  args:
    - tests/udf_test_utils.py
    - --generate-js-libs-package-json
  ###########################################################
  # Install npm packages based off the package.json file
  # created in the previous step.
  ###########################################################
- name: node
  id: install_npm_packages
  entrypoint: npm
  args:
    - install
  ############################################################
  # Dynamically create webpack config files needed by webpack
  # to build npm packages into single .js files which will be
  # hosted on GCS and used by BigQuery UDFs.
  ############################################################
- name: gcr.io/bqutil/bq_udf_ci
  id: generate_webpack_configs
  entrypoint: python3
  args:
    - tests/udf_test_utils.py
    - --generate-webpack-configs
  waitFor:
    - install_npm_packages
    - generate_js_libs_package_json
  ###########################################################
  # Build (via webpack) all js libraries for BigQuery UDFs
  ###########################################################
- name: node
  id: build_bq_js_libs
  entrypoint: npm
  args:
    - run-script
    - build-all-libs
  waitFor:
    - generate_webpack_configs
    - install_npm_packages
  ###########################################################
  # Copy all libs to GCS bucket
  ###########################################################
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: copy_js_to_gcs
  entrypoint: gsutil
  args:
    - '-m'
    - cp
    - js_builds/*
    - ${_JS_BUCKET}
  waitFor:
    - build_bq_js_libs
timeout: 1800s # 30 minutes
options:
  machineType: N1_HIGHCPU_32
