pipeline {
    agent { docker { image 'dataformco/dataform' } }
    environment {
        GOOGLE_APPLICATION_CREDENTIALS = credentials('service_acct')
    }
    stages {
        stage('dataform_tests') {
            steps {
                dir('udfs/tests/dataform_testing_framework'){
                    sh 'dataform --help'
                }
            }
        }
    }
}