pipeline {
    agent { docker { image 'python:3.8.0' } }
    environment {
        GOOGLE_APPLICATION_CREDENTIALS = credentials('service_acct')
    }
    stages {
        stage('install_requirements') {
            steps {
                dir('tools/cloud_functions/gcs_event_based_ingest/'){
                    sh '''
                        python -m venv venv
                        . venv/bin/activate
                        pip install -r requirements-dev.txt
                    '''
                }
            }
        }
        stage('unit_tests') {
            steps {
                dir('tools/cloud_functions/gcs_event_based_ingest/'){
                    sh 'venv/bin/python3 -m pytest tests -m "not IT"'
                }
            }
        }
        stage('integration_tests') {
            steps {
                dir('tools/cloud_functions/gcs_event_based_ingest/'){
                    sh 'venv/bin/python3 -m pytest tests -m IT'
                }
            }
        }
    }
}