# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
config {
    type: "view",
    schema: "dev_data_zone",
    name: "date_assertions_test",
    tags:["date_assertions_unit_test", "all_test"],
    assertions: {
        nonNull: ["test_date"],
        rowConditions: 
        [
            date_assertions.test_future_date("test_date"),
            date_assertions.test_valid_years("test_date"),
            date_assertions.test_date_format("test_date", "yyyy/mm/dd")
        ]
    }
}

/* 
    This test should fail 2 assertions
 */

/*
    test_future_date
    Methods should return fasle if a date is future
*/
SELECT "1997/11/03" AS test_date UNION ALL    --This should pass 
SELECT "2008/08/08" AS test_date UNION ALL    --This should pass
SELECT "2025/03/24" AS test_date UNION ALL             --This should fail

/*
    test_valid_years
    Methods should return fasle if a person is above 100 years old
*/
SELECT "1997/11/03" AS test_date UNION ALL    --This should pass 
SELECT "2008/08/08" AS test_date UNION ALL    --This should pass
SELECT "1769/03/24" AS test_date              --This should fail
