# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config {
    type: "view",
    schema: "dev_data_zone",
    name: "email_assertion_test",
    tags:["email_assertion_unit_test","all_test"],
    assertions: {
        nonNull: ["test_email"],
        rowConditions: 
        [
            personal_info_assertions.test_email_validity("test_email")
        ]
    }
}

/* 
    This test should fail 1 assertion
 */

/*
    test_email_validity
    Return false is email is not in the foramt of abc@xyc.com or other
*/
SELECT "george.bail@google.com" AS test_email UNION ALL    --This should pass 
SELECT "among.us@amongus.net" AS test_email UNION ALL    --This should pass
SELECT "1736#$%.com" AS test_email              --This should fail
