# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config {
    type: "view",
    schema: "dev_data_zone",
    name: "marital_status_assertion_test",
    tags:["marital_status_assertion_unit_test","all_test"],
    assertions: {
        nonNull: ["test_marital"],
        rowConditions: 
        [
            personal_info_assertions.test_marital_status("test_marital")
        ]
    }
}

/* 
    This test should fail 1 assertion
 */

/*
    test_marital_status
    Return false if marital status is not in the list defined Married, Single, Divorced, Widowed
*/
SELECT "Married" AS test_marital UNION ALL    --This should pass 
SELECT "Divorced" AS test_marital UNION ALL    --This should pass
SELECT "Happy" AS test_marital              --This should fail
