package com.google.cloud.bigquery.utils.queryfixer.errors;

import com.google.cloud.bigquery.BigQueryException;
import com.google.cloud.bigquery.utils.queryfixer.entity.Position;

import lombok.Getter;

/**
 * The base class to represent the SQL Error generated by the BigQuery server. It should be resolved
 * from {@link BigQueryException}.
 */
@Getter
public abstract class BigQuerySqlError {

  private final BigQueryException errorSource;
  /**
   * The occurrence of the error at a query. It may be null if the error does not belong to any
   * specific locations.
   */
  private final Position errorPosition;

  public BigQuerySqlError(Position errorPosition, BigQueryException errorSource) {
    this.errorPosition = errorPosition;
    this.errorSource = errorSource;
  }

  public String getMessage() {
    return errorSource.getMessage();
  }
}
