package com.google.cloud.bigquery.utils.queryfixer.errors;

import com.google.cloud.bigquery.BigQueryException;
import com.google.cloud.bigquery.utils.queryfixer.entity.Position;
import lombok.Getter;

/**
 * The base class to represent the SQL Error generated by the BigQuery server. It should be resolved
 * from {@link BigQueryException}.
 */
@Getter
public abstract class BigQuerySqlError {

  private final BigQueryException errorSource;

  /**
   * The occurrence of the error at a query. It may be null if the error does not belong to any
   * specific locations. This field is not final, because the original error message may not contain
   * position information, but later the query fixer may locate the error and specify the error
   * position.
   */
  private Position errorPosition;

  public BigQuerySqlError(Position errorPosition, BigQueryException errorSource) {
    this.errorPosition = errorPosition;
    this.errorSource = errorSource;
  }

  public String getMessage() {
    return errorSource.getMessage();
  }

  public void setErrorPosition(Position errorPosition) {
    this.errorPosition = errorPosition;
  }
}
