package com.google.cloud.bigquery.utils.queryfixer.errors;

import com.google.cloud.bigquery.BigQueryException;
import com.google.cloud.bigquery.utils.queryfixer.entity.Position;

import lombok.Getter;

/** The base class to represent the SQL Error generated by the BigQuery server. It should be resolved from
 * {@link BigQueryException}. */
@Getter
public abstract class BigQuerySqlError {

  BigQueryException errorSource;
  /** The occurrence of the error at a query. It may be null if the error does not belong to any specific locations. */
  Position errPos;

  public BigQuerySqlError(Position errPos, BigQueryException errorSource) {
    this.errPos = errPos;
    this.errorSource = errorSource;
  }
}
