# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config {
    type: "test",
    dataset: "date_assertions"
}

js {
    const test_cases = {
        // Assertions that pass
        "1997/11/03" : "TRUE",
        "2008/08/08" : "TRUE",
        "1996/11/03" : "TRUE",
        "2005/04/13" : "TRUE",
        "1998/11/03" : "TRUE",
        "2006/07/29" : "TRUE",

        //Assertions that fail
        "2025/03/24" : "FALSE",
        "1769/03/24" : "FALSE"
    };
    let expected_output_select_statements = [];
    let test_input_select_statements = [];
    for(var test_name in test_cases) {
        test_input_select_statements.push(`SELECT "${test_name}" AS test_date`);
        expected_output_select_statements.push(`SELECT ${test_cases[test_name]} AS is_valid_date`);
    }
}

input "test_dates" {
    ${test_input_select_statements.join(' UNION ALL\n')}
}

-- Expected Outputs
${expected_output_select_statements.join(' UNION ALL\n')}
