package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "util",
    srcs = ["util.cc"],
    hdrs = ["util.h"],
    deps = [
        "@com_google_zetasql//zetasql/parser:parse_tree",
        "@com_google_zetasql//zetasql/public:analyzer",
        "@com_google_zetasql//zetasql/public:parse_helpers",
    ],
)
